# Generated by Django 5.0.1 on 2025-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceorder',
            options={'ordering': ['-completion_date'], 'verbose_name': 'Ordem de Manutenção', 'verbose_name_plural': 'Ordens de Manutenção'},
        ),
        migrations.RemoveField(
            model_name='maintenanceorder',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Nota Fiscal (PDF/Imagem)'),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número da Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='warranty_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento da Garantia'),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='warranty_terms',
            field=models.TextField(blank=True, verbose_name='Termos da Garantia'),
        ),
        migrations.AlterField(
            model_name='maintenanceorder',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Manutenção'),
        ),
        migrations.AlterField(
            model_name='maintenanceorder',
            name='service_provider',
            field=models.CharField(blank=True, max_length=200, verbose_name='Empresa Prestadora do Serviço'),
        ),
        migrations.AlterField(
            model_name='maintenanceorder',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='concluida', max_length=20, verbose_name='Status'),
        ),
    ]
